name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  check-pull-request:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test
  test:
    name: Run Journey Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t defradigital/cdp-portal-backend:${{github.sha}} .
      - uses: DEFRA/cdp-portal-journey-tests/run-journey-tests@main
        with:
          portal-backend: ${{github.sha}}
  sonarcloud-scan:
    name: CDP SonarCloud Scan
    uses: ./.github/workflows/sonarcloud.yml
    needs: check-pull-request
    secrets: inherit